#!/usr/bin/env bash
# uninstall.sh — Remove every trace of the Claude Code governance framework
#
# Usage: ./uninstall.sh
#
# Removes (local, per-repo):
#   • Dev guide and implementation package files copied to repo root
#   • .githooks/gate.sh, pre-commit, pre-push, verify_governance_integrity.sh
#     (and the .githooks/ directory itself, once empty)
#   • git config core.hooksPath (restores git default)
#   • git config remote.origin.{push,fetch} bypass note refspecs
#   • .github/workflows/gate.yml
#   • .mcp.json
#   • .claude/ directory (gate_state.json, baseline.json, session_state.json,
#                         session_spend.tmp, git_cache.json, graph.pid,
#                         checkpoints/, commands/, hooks/, checkpoint_tool.py,
#                         gate_integrity.sha256, settings.json)
#   • quarantine.txt (if it matches the framework template)
#   • Framework entries from .gitignore
#
# Removes (global, machine-wide):
#   • ~/.claude/org_policy.json (if written by install.sh)
#   • code-review-graph pipx package
#
# Handled with a SEPARATE explicit prompt, never auto-removed silently — all
# three may contain significant human-authored content by the time you
# uninstall, and a blind rm -rf here would be a real way to lose real work:
#   • CLAUDE.md (generated by Claude Code during init)
#   • docs/PRD.md, TRD.md, DB_SCHEMA.md, USER_FLOWS.md, SYSTEM_DESIGN.md,
#     ARCHITECTURE_DECISIONS.md (generated by the greenfield spec-gate phase,
#     if present — reviewed and approved by a human before Phase B ever ran)
#
# NEVER touched, on purpose, not by omission: the four-layer scaffold
# (src/domain/, src/application/, src/infrastructure/, src/presentation/,
# tests/) and anything inside it. By the time anyone runs this uninstaller,
# that scaffold is almost certainly real application code, not framework
# boilerplate — this uninstaller removes governance tooling, never your code.

set -euo pipefail

GRAPH_PACKAGE="code-review-graph"
ORG_POLICY_PATH="${HOME}/.claude/org_policy.json"

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; RESET='\033[0m'

_info()    { echo -e "${BLUE}[uninstall]${RESET} $*"; }
_success() { echo -e "${GREEN}[uninstall]${RESET} ✓ $*"; }
_warn()    { echo -e "${YELLOW}[uninstall]${RESET} ⚠ $*"; }
_error()   { echo -e "${RED}[uninstall]${RESET} ✗ $*" >&2; exit 1; }

_rm() {
    local target="$1"
    if [ -e "$target" ] || [ -L "$target" ]; then
        rm -rf "$target"
        _success "Removed: $target"
    fi
}

_confirm() {
    # ${var,,} (lowercase expansion) is bash 4+ only. macOS ships bash 3.2 as
    # /bin/bash by default (Apple never ships GPLv3 bash) and does not
    # upgrade it — most Mac users never install a newer bash via Homebrew,
    # so this is the common case, not an edge case. Case-insensitive `case`
    # pattern matching works identically on bash 3.2 and 5.x.
    local answer
    read -r -p "$1 [y/N] " answer </dev/tty
    case "$answer" in
        [Yy]|[Yy][Ee][Ss]) return 0 ;;
        *) return 1 ;;
    esac
}

# Intentionally duplicated from install.sh rather than sourced from a shared
# file — both scripts are meant to be standalone/single-file (same reason
# _rm, _confirm, and the color vars above are already duplicated instead of
# shared). Keep the two copies in sync if either changes.
_bounded_git_fetch() {
    # Usage: _bounded_git_fetch <repo_dir> — a real, hard wall-clock bound on
    # `git fetch`, with no external `timeout` binary (unavailable by default
    # on macOS). git's own http.lowSpeedLimit/http.lowSpeedTime only bound
    # the TRANSFER phase — they do nothing for a slow/hanging DNS lookup or
    # TCP connect, which is exactly the case that hung for multiple minutes
    # in testing (no network reachable to the remote at all). Backgrounds
    # the fetch and polls for up to 5 real wall-clock seconds regardless of
    # which phase it's stuck in, then kills it. Best-effort: returns
    # non-zero on timeout or fetch failure, never raises.
    local repo_dir="$1"
    GIT_TERMINAL_PROMPT=0 git -c http.lowSpeedLimit=1000 -c http.lowSpeedTime=5 -C "$repo_dir" fetch --quiet 2>/dev/null &
    local fetch_pid=$!
    local waited=0
    while kill -0 "$fetch_pid" 2>/dev/null && [ "$waited" -lt 5 ]; do
        sleep 1
        waited=$((waited + 1))
    done
    if kill -0 "$fetch_pid" 2>/dev/null; then
        kill -9 "$fetch_pid" 2>/dev/null
        wait "$fetch_pid" 2>/dev/null
        return 1
    fi
    wait "$fetch_pid" 2>/dev/null
}

_check_framework_staleness() {
    # This framework is meant to be cloned ONCE to a persistent local path
    # (e.g. ~/ai-dev-workflow) and reused across many target repos — nothing
    # here auto-updates it. install.sh had this exact gap: a user ran an old
    # local clone and got confusing behavior with no indication their copy
    # was out of date. Same risk applies here (running an old uninstall.sh
    # means missing bug fixes to uninstall.sh itself). Best-effort only:
    # never blocks, never requires network (silently skips if the fetch
    # fails), and never touches the working tree (fetch only, no pull).
    #
    # AI_DEV_WORKFLOW_SKIP_STALENESS_CHECK=1 skips this entirely — see
    # install.sh's copy of this function for the full rationale (kept in
    # sync, same reason the whole function is duplicated rather than shared).
    [ "${AI_DEV_WORKFLOW_SKIP_STALENESS_CHECK:-0}" = "1" ] && return 0
    local repo_dir="$1"
    git -C "$repo_dir" rev-parse --git-dir >/dev/null 2>&1 || return 0
    local upstream
    upstream=$(git -C "$repo_dir" rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null || echo "")
    [ -n "$upstream" ] || return 0
    _bounded_git_fetch "$repo_dir" || return 0
    local behind
    behind=$(git -C "$repo_dir" rev-list --count "HEAD..${upstream}" 2>/dev/null || echo "0")
    case "$behind" in ''|*[!0-9]*) return 0 ;; esac
    [ "$behind" -gt 0 ] || return 0
    echo ""
    echo "⚠ Your local ai-dev-workflow clone (${repo_dir}) is ${behind} commit(s)"
    echo "  behind ${upstream} — you may be missing recent fixes, including to"
    echo "  this uninstaller itself."
    echo "  Recommended: git -C '${repo_dir}' pull, then re-run this uninstaller."
    echo ""
}

# ── Preflight ─────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Claude Code Governance Framework — Uninstaller"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

git rev-parse --git-dir >/dev/null 2>&1 || _error "Not inside a git repository."
REPO_ROOT=$(git rev-parse --show-toplevel)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

_check_framework_staleness "$SCRIPT_DIR"

# Guard: refuse to run against the ai-dev-workflow repo itself
if [ "$REPO_ROOT" = "$SCRIPT_DIR" ]; then
    _error "You are inside the ai-dev-workflow framework repo — not your target repo.
       cd into the repo where you ran install.sh, then run:
         ${SCRIPT_DIR}/uninstall.sh"
fi

cd "$REPO_ROOT"

# Detect via ANY known install artifact, not gate_state.json alone. That file
# is gitignored in most target repos (it's a local ledger, not committed
# governance content), so a partial/interrupted install, a fresh clone of a
# governed repo, or simply a prior `rm -rf .claude` mid-session left every
# other artifact (.githooks/, CLAUDE.md, .claude/settings.json, .mcp.json)
# in place while this single-file check reported "nothing to remove" and
# refused to run — a real, reproducible dead end with no way to clean up
# short of hand-deleting files. Any ONE governance artifact existing is
# enough to proceed; the removal loops below already independently guard
# each file/directory with its own existence check, so listing more
# detection candidates here is safe — it only widens when the uninstaller is
# willing to start, never what it deletes.
_governed_repo_detected() {
    [ -f ".claude/gate_state.json" ] && return 0
    [ -f ".githooks/gate.sh" ] && return 0
    [ -f ".claude/hooks/pre_bash_trust_root_guard.sh" ] && return 0
    [ -f ".claude/checkpoint_tool.py" ] && return 0
    [ -f ".claude/settings.json" ] && grep -q "pre_bash_trust_root_guard" ".claude/settings.json" 2>/dev/null && return 0
    [ -f ".github/workflows/gate.yml" ] && grep -q "gate\.sh" ".github/workflows/gate.yml" 2>/dev/null && return 0
    [ -f ".mcp.json" ] && grep -q "code-review-graph" ".mcp.json" 2>/dev/null && return 0
    return 1
}
_governed_repo_detected || _error "No governed repo detected (checked .claude/gate_state.json, .githooks/gate.sh, .claude/hooks/pre_bash_trust_root_guard.sh, .claude/checkpoint_tool.py, .claude/settings.json, .github/workflows/gate.yml, .mcp.json — none found). Nothing to remove."

# ── Build removal manifest ────────────────────────────────────────────────────
_info "Scanning for installed framework artifacts..."

LOCAL_FILES=()
LOCAL_DIRS=()
GITCONFIG_ENTRIES=()
GITIGNORE_ENTRIES=()

# Dev guide and init package (either basket)
for f in \
    "v1_claude_code_development_guide_new.md" \
    "v1_claude_code_development_guide_existing.md" \
    "v1_implementation_package_new.md" \
    "v1_implementation_package_existing.md"
do
    [ -f "$f" ] && LOCAL_FILES+=("$f")
done

# quarantine.txt — only if it contains the framework header
if [ -f "quarantine.txt" ] && grep -q "QUARANTINE FILE — Claude Code Governance Framework" quarantine.txt 2>/dev/null; then
    LOCAL_FILES+=("quarantine.txt")
fi

# .githooks entries created by install.sh (_write_hooks writes all four —
# verify_governance_integrity.sh was missing here for a while, which meant
# it never got removed, which meant .githooks/ never became empty, which
# meant the whole directory silently survived every uninstall run)
for f in ".githooks/gate.sh" ".githooks/pre-commit" ".githooks/pre-push" ".githooks/verify_governance_integrity.sh"; do
    [ -f "$f" ] && LOCAL_FILES+=("$f")
done

# CI workflow — only if it contains gate.sh references
if [ -f ".github/workflows/gate.yml" ] && grep -q "gate\.sh" ".github/workflows/gate.yml" 2>/dev/null; then
    LOCAL_FILES+=(".github/workflows/gate.yml")
fi

# .mcp.json
[ -f ".mcp.json" ] && grep -q "code-review-graph" ".mcp.json" 2>/dev/null && LOCAL_FILES+=(".mcp.json")

# .claude/ directory
[ -d ".claude" ] && LOCAL_DIRS+=(".claude")

# git config entries
if git config --get core.hooksPath 2>/dev/null | grep -q "^\.githooks$" 2>/dev/null; then
    GITCONFIG_ENTRIES+=("core.hooksPath (.githooks)")
fi
if git config --get-all remote.origin.push 2>/dev/null | grep -q "refs/notes/bypasses" 2>/dev/null; then
    GITCONFIG_ENTRIES+=("remote.origin.push bypass refspec")
fi
if git config --get-all remote.origin.fetch 2>/dev/null | grep -q "refs/notes/bypasses" 2>/dev/null; then
    GITCONFIG_ENTRIES+=("remote.origin.fetch bypass refspec")
fi

# .gitignore entries added by install.sh
FRAMEWORK_GITIGNORE_ENTRIES=(
    ".claude/session_state.json"
    ".claude/session_spend.tmp"
    ".claude/git_cache.json"
    ".claude/checkpoints/"
    "__pycache__/"
    "*.pyc"
)
if [ -f ".gitignore" ]; then
    for entry in "${FRAMEWORK_GITIGNORE_ENTRIES[@]}"; do
        grep -qF "$entry" .gitignore 2>/dev/null && GITIGNORE_ENTRIES+=("$entry")
    done
fi

# ── Print manifest ─────────────────────────────────────────────────────────────
echo "Everything below will be permanently removed from ${REPO_ROOT}:"
echo ""

if [ ${#LOCAL_FILES[@]} -gt 0 ]; then
    echo "  Files:"
    for f in "${LOCAL_FILES[@]}"; do echo "    • $f"; done
fi
if [ ${#LOCAL_DIRS[@]} -gt 0 ]; then
    echo "  Directories:"
    for d in "${LOCAL_DIRS[@]}"; do echo "    • $d/ (and all contents)"; done
fi
if [ ${#GITCONFIG_ENTRIES[@]} -gt 0 ]; then
    echo "  Git config:"
    for c in "${GITCONFIG_ENTRIES[@]}"; do echo "    • $c"; done
fi
if [ ${#GITIGNORE_ENTRIES[@]} -gt 0 ]; then
    echo "  .gitignore entries:"
    for e in "${GITIGNORE_ENTRIES[@]}"; do echo "    • $e"; done
fi

echo ""
echo "  Global (machine-wide):"
[ -f "$ORG_POLICY_PATH" ] && echo "    • ${ORG_POLICY_PATH}" || echo "    • ${ORG_POLICY_PATH} (not found — skipping)"
if command -v pipx >/dev/null 2>&1 && pipx list 2>/dev/null | grep -q "$GRAPH_PACKAGE"; then
    echo "    • pipx package: ${GRAPH_PACKAGE}"
else
    echo "    • pipx package: ${GRAPH_PACKAGE} (not installed — skipping)"
fi

CLAUDE_MD_NOTE=""
if [ -f "CLAUDE.md" ]; then
    echo ""
    echo "  CLAUDE.md: exists — will be handled with a separate prompt"
    CLAUDE_MD_NOTE="yes"
fi

# Spec docs from the greenfield spec-gate phase (Phase A.5) — a human
# reviewed and approved these before Phase B ever ran, so they get the same
# separate-explicit-prompt treatment as CLAUDE.md, never bundled into the
# single blanket confirmation below.
DOC_SPEC_FILES=()
for f in \
    "docs/PRD.md" "docs/TRD.md" "docs/DB_SCHEMA.md" \
    "docs/USER_FLOWS.md" "docs/SYSTEM_DESIGN.md" "docs/ARCHITECTURE_DECISIONS.md"
do
    [ -f "$f" ] && DOC_SPEC_FILES+=("$f")
done
if [ ${#DOC_SPEC_FILES[@]} -gt 0 ]; then
    echo ""
    echo "  docs/ spec files: found ${#DOC_SPEC_FILES[@]} — will be handled with a separate prompt"
    for f in "${DOC_SPEC_FILES[@]}"; do echo "    • $f"; done
fi

echo ""
echo "  NOT touched, on purpose: the four-layer scaffold (src/domain/,"
echo "  src/application/, src/infrastructure/, src/presentation/, tests/) and"
echo "  anything inside it — that's almost certainly your real application"
echo "  code by now, not framework boilerplate. This uninstaller removes"
echo "  governance tooling only, never application code."

echo ""

# ── Single confirmation ────────────────────────────────────────────────────────
_confirm "Remove everything listed above?" || { echo "Aborted."; exit 0; }

echo ""
_info "Removing framework artifacts..."

# ── Local files ────────────────────────────────────────────────────────────────
for f in "${LOCAL_FILES[@]}"; do _rm "$f"; done
for d in "${LOCAL_DIRS[@]}"; do _rm "$d"; done

# Remove .githooks/ directory if now empty
if [ -d ".githooks" ] && [ -z "$(ls -A .githooks 2>/dev/null)" ]; then
    rmdir .githooks
    _success "Removed empty directory: .githooks/"
fi

# ── Git config cleanup ─────────────────────────────────────────────────────────
if git config --get core.hooksPath 2>/dev/null | grep -q "^\.githooks$"; then
    git config --unset core.hooksPath
    _success "Unset git config core.hooksPath (restored to git default)"
fi

while git config --get-all remote.origin.push 2>/dev/null | grep -q "refs/notes/bypasses"; do
    git config --unset remote.origin.push "refs/notes/bypasses:refs/notes/bypasses" 2>/dev/null || break
done
while git config --get-all remote.origin.fetch 2>/dev/null | grep -q "refs/notes/bypasses"; do
    git config --unset remote.origin.fetch "\\+refs/notes/bypasses:refs/notes/bypasses" 2>/dev/null || \
    git config --unset remote.origin.fetch "refs/notes/bypasses" 2>/dev/null || break
done
[ ${#GITCONFIG_ENTRIES[@]} -gt 0 ] && _success "Removed git config bypass note refspecs"

# ── .gitignore cleanup ────────────────────────────────────────────────────────
if [ ${#GITIGNORE_ENTRIES[@]} -gt 0 ] && [ -f ".gitignore" ]; then
    for entry in "${FRAMEWORK_GITIGNORE_ENTRIES[@]}"; do
        python3 -c "
import sys
entry = sys.argv[1]
lines = open('.gitignore').readlines()
open('.gitignore', 'w').writelines(l for l in lines if l.rstrip('\n') != entry)
" "$entry" 2>/dev/null || true
    done
    _success "Removed framework entries from .gitignore"
fi

# ── Global resources ──────────────────────────────────────────────────────────
echo ""
_info "Removing global resources..."

if [ -f "$ORG_POLICY_PATH" ]; then
    if grep -q "Org-wide Claude Code token budget" "$ORG_POLICY_PATH" 2>/dev/null; then
        _rm "$ORG_POLICY_PATH"
    else
        _warn "Skipping ${ORG_POLICY_PATH} — contents appear user-modified. Remove manually if needed."
    fi
fi

if command -v pipx >/dev/null 2>&1 && pipx list 2>/dev/null | grep -q "$GRAPH_PACKAGE"; then
    pipx uninstall "$GRAPH_PACKAGE" --quiet 2>&1 | tail -3 || \
        _warn "pipx uninstall failed — remove manually: pipx uninstall ${GRAPH_PACKAGE}"
    _success "Removed pipx package: ${GRAPH_PACKAGE}"
fi

# ── CLAUDE.md — always a separate explicit prompt ──────────────────────────────
if [ -n "$CLAUDE_MD_NOTE" ]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    _warn "CLAUDE.md was not removed automatically."
    echo ""
    echo "  CLAUDE.md is generated by Claude Code during init and may"
    echo "  contain significant human-authored architectural decisions."
    echo ""
    if _confirm "Remove CLAUDE.md permanently?"; then
        _rm "CLAUDE.md"
    else
        _warn "Kept: CLAUDE.md — remove manually if desired."
    fi
fi

# ── docs/ spec files — always a separate explicit prompt ───────────────────────
if [ ${#DOC_SPEC_FILES[@]} -gt 0 ]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    _warn "docs/ spec files were not removed automatically."
    echo ""
    echo "  These were drafted by the greenfield spec-gate phase and reviewed"
    echo "  and approved by a human before any code was written — they may"
    echo "  still be the most current PRD/TRD/schema/flows for this project."
    echo ""
    if _confirm "Remove all ${#DOC_SPEC_FILES[@]} docs/ spec file(s) permanently?"; then
        for f in "${DOC_SPEC_FILES[@]}"; do _rm "$f"; done
        rmdir docs 2>/dev/null && _success "Removed empty directory: docs/" || true
    else
        _warn "Kept: docs/ spec files — remove manually if desired."
    fi
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN} Uninstall complete${RESET}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To commit the removal:"
echo "  git add -u"
echo "  git commit -m 'chore: remove Claude Code governance framework'"
echo ""
