#!/usr/bin/env bash
# gate.sh — Claude Code enforcement gate (generated by install.sh, committed to .githooks/)
# Called by pre-commit and pre-push hooks. Never invoke directly in CI.
#
# STACK-SPECIFIC VARIABLES (filled by init — do not edit manually):
TEST_CMD="${TEST_CMD:-pytest -x -q --cov=src --cov-fail-under=80}"
LINT_CMD="${LINT_CMD:-ruff check src/}"
TYPE_CMD="${TYPE_CMD:-mypy src/}"
COVERAGE_CMD="${COVERAGE_CMD:-pytest --cov=src --cov-report=term-missing}"
COMPLEXITY_CMD="${COMPLEXITY_CMD:-radon cc -n C src/}"
FRONTEND_TEST_CMD="${FRONTEND_TEST_CMD:-}"   # empty = skip
FRONTEND_LINT_CMD="${FRONTEND_LINT_CMD:-}"   # empty = skip
FRONTEND_TYPE_CMD="${FRONTEND_TYPE_CMD:-}"   # empty = skip

set -euo pipefail

# ── Constants ────────────────────────────────────────────────────────────────
GATE_STATE=".claude/gate_state.json"
SESSION_SPEND=".claude/session_spend.tmp"
GIT_CACHE=".claude/git_cache.json"
ORG_POLICY="${HOME}/.claude/org_policy.json"
RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; RESET='\033[0m'

# ── Helpers ───────────────────────────────────────────────────────────────────

_json_get() {
    # Usage: _json_get <file> <key>  — naive but dependency-free jq substitute
    python3 -c "
import json, sys
with open('$1') as f:
    d = json.load(f)
keys = '$2'.split('.')
v = d
for k in keys:
    if k == '': break
    v = v.get(k, '')
print(v if v is not None else '')
" 2>/dev/null || echo ""
}

_json_set() {
    # Usage: _json_set <file> <key> <value>
    python3 -c "
import json, sys
with open('$1') as f:
    d = json.load(f)
keys = '$2'.split('.')
obj = d
for k in keys[:-1]:
    obj = obj.setdefault(k, {})
val = '$3'
try:
    obj[keys[-1]] = json.loads(val)
except:
    obj[keys[-1]] = val
with open('$1', 'w') as f:
    json.dump(d, f, indent=2)
" 2>/dev/null
}

_json_append_audit() {
    # Append one entry to token.token_audit_log; prune entries older than 90 days
    python3 -c "
import json, sys
from datetime import datetime, timedelta
with open('$GATE_STATE') as f:
    d = json.load(f)
entry = {'timestamp': '$1', 'trigger': '$2', 'spend_at_run': $3, 'outcome': '$4'}
log = d.get('token', {}).get('token_audit_log', [])
log.append(entry)
cutoff = (datetime.utcnow() - timedelta(days=90)).isoformat()
log = [e for e in log if e.get('timestamp','') >= cutoff]
d.setdefault('token', {})['token_audit_log'] = log
with open('$GATE_STATE', 'w') as f:
    json.dump(d, f, indent=2)
" 2>/dev/null
}

_run_with_timeout() {
    local timeout_sec cmd_label
    timeout_sec=$(_json_get "$GATE_STATE" "thresholds.command_timeout_sec")
    timeout_sec="${timeout_sec:-30}"
    cmd_label="$1"; shift
    # Use timeout(1) if available; fall back to plain execution
    if command -v timeout >/dev/null 2>&1; then
        if ! timeout "$timeout_sec" "$@" 2>&1; then
            local exit_code=$?
            if [ $exit_code -eq 124 ]; then
                echo -e "${YELLOW}⚠ TIMEOUT: '$cmd_label' exceeded ${timeout_sec}s — killed and logged${RESET}" >&2
                _json_append_audit "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "timeout" 0 "timeout:${cmd_label}"
                return 1
            fi
            return $exit_code
        fi
    else
        "$@"
    fi
}

# ── CRASH GUARD ───────────────────────────────────────────────────────────────
# Any unhandled non-zero exit from gate.sh is a BLOCK, never a silent pass.
# stderr is emitted verbatim so the engineer sees the root cause.
_crash_handler() {
    echo -e "${RED}GATE CRASH at line $1 — exit $2. Commit blocked. Fix gate.sh or contact platform team.${RESET}" >&2
    exit 1
}
trap '_crash_handler ${LINENO} $?' ERR

# ── GATE_STATE guard ──────────────────────────────────────────────────────────
if [ ! -f "$GATE_STATE" ]; then
    echo -e "${YELLOW}⚠ gate_state.json not found — running cold start (full scan)${RESET}" >&2
fi

# ── STEP 1: BRANCH VALIDATION ─────────────────────────────────────────────────
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [[ "$CURRENT_BRANCH" =~ ^(main|master|develop)$ ]]; then
    echo -e "${RED}BRANCH BLOCK: Direct commits to '$CURRENT_BRANCH' are forbidden.${RESET}" >&2
    echo "Create a feature/bugfix/hotfix/release branch." >&2
    exit 1
fi

BRANCH_PREFIX="${CURRENT_BRANCH%%/*}"
if [[ ! "$BRANCH_PREFIX" =~ ^(feature|bugfix|hotfix|release)$ ]] && [ -n "$CURRENT_BRANCH" ]; then
    echo -e "${YELLOW}⚠ Branch '$CURRENT_BRANCH' does not follow Gitflow naming.${RESET}" >&2
    # Warn only — do not block; human-facing warning is sufficient at gate level
fi

# ── STEP 2: TOKEN HARNESS ─────────────────────────────────────────────────────
TODAY=$(date +%Y-%m-%d)
GATE_TRIGGER="${GATE_TRIGGER:-pre-commit}"   # pre-commit or pre-push hook sets this
NOW_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Read org-level budget ceiling
ORG_BUDGET=""
if [ -f "$ORG_POLICY" ]; then
    ORG_BUDGET=$(python3 -c "import json; d=json.load(open('$ORG_POLICY')); print(d.get('TOKEN_BUDGET',''))" 2>/dev/null || echo "")
fi

TOKEN_BUDGET=""
if [ -f "$GATE_STATE" ]; then
    TOKEN_BUDGET=$(_json_get "$GATE_STATE" "token.token_budget")
fi
TOKEN_BUDGET="${TOKEN_BUDGET:-50000}"

# Org ceiling wins if set and lower than repo setting
if [ -n "$ORG_BUDGET" ] && [ "$ORG_BUDGET" -lt "$TOKEN_BUDGET" ] 2>/dev/null; then
    TOKEN_BUDGET="$ORG_BUDGET"
fi

# Date-roll reset
if [ -f "$GATE_STATE" ]; then
    LAST_RESET=$(_json_get "$GATE_STATE" "token.token_last_reset")
    if [ "$LAST_RESET" != "$TODAY" ]; then
        _json_set "$GATE_STATE" "token.token_spent_today" "0"
        _json_set "$GATE_STATE" "token.token_last_reset" "\"$TODAY\""
    fi
fi

# Accumulate session spend from tmp file
SESSION_SPEND_VAL=0
if [ -f "$SESSION_SPEND" ]; then
    SESSION_SPEND_VAL=$(cat "$SESSION_SPEND" 2>/dev/null | tr -cd '0-9' || echo "0")
    SESSION_SPEND_VAL="${SESSION_SPEND_VAL:-0}"
fi

SPENT_TODAY=0
if [ -f "$GATE_STATE" ]; then
    SPENT_TODAY=$(_json_get "$GATE_STATE" "token.token_spent_today")
    SPENT_TODAY="${SPENT_TODAY:-0}"
fi
TOTAL_SPENT=$(( SPENT_TODAY + SESSION_SPEND_VAL ))

# Threshold evaluation
OUTCOME="pass"
if [ "$TOKEN_BUDGET" -gt 0 ] 2>/dev/null; then
    PCT=$(( TOTAL_SPENT * 100 / TOKEN_BUDGET ))
    if [ "$PCT" -ge 100 ]; then
        echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2
        echo "TOKEN HARD BLOCK — Org-wide daily budget exhausted." >&2
        echo "Spent: ${TOTAL_SPENT} / Budget: ${TOKEN_BUDGET} tokens" >&2
        echo "Resets: tomorrow (${TODAY} 00:00 UTC)" >&2
        echo "To raise budget: update ~/.claude/org_policy.json TOKEN_BUDGET (requires human PR)." >&2
        echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}" >&2
        OUTCOME="hard_block"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "hard_block"
        [ -f "$GATE_STATE" ] && _json_set "$GATE_STATE" "token.token_spent_today" "$TOTAL_SPENT"
        exit 1
    elif [ "$PCT" -ge 80 ]; then
        echo -e "${YELLOW}⚠ TOKEN WARNING: ${PCT}% of daily budget used (${TOTAL_SPENT}/${TOKEN_BUDGET})${RESET}" >&2
        OUTCOME="warn"
    fi
fi

# ── STEP 3: GRAPH STALENESS CHECK ─────────────────────────────────────────────
if [ -f ".mcp.json" ] && [ -f "$GATE_STATE" ]; then
    LAST_BUILD=$(_json_get "$GATE_STATE" "mcp_graph.last_build_timestamp")
    if [ -n "$LAST_BUILD" ] && [ "$LAST_BUILD" != "null" ]; then
        # Check if last build > 7 days ago (portable: compare epoch seconds)
        LAST_BUILD_EPOCH=$(date -d "$LAST_BUILD" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$LAST_BUILD" +%s 2>/dev/null || echo "0")
        NOW_EPOCH=$(date +%s)
        STALE_THRESHOLD=$(( 7 * 24 * 3600 ))
        if [ $(( NOW_EPOCH - LAST_BUILD_EPOCH )) -gt "$STALE_THRESHOLD" ]; then
            echo -e "${YELLOW}⚠ GRAPH STALE: last built >7 days ago. Run: code-review-graph build${RESET}" >&2
        fi
    fi
fi

# ── STEP 4: DETERMINE SCAN SCOPE ──────────────────────────────────────────────
# Incremental scan from last_pass_sha; cold start if null or missing
LAST_SHA=""
if [ -f "$GATE_STATE" ]; then
    LAST_SHA=$(_json_get "$GATE_STATE" "last_pass_sha")
fi

HEAD_SHA=$(git rev-parse HEAD 2>/dev/null || echo "INIT")

if [ -z "$LAST_SHA" ] || [ "$LAST_SHA" = "null" ] || [ "$LAST_SHA" = "" ]; then
    echo "GATE: cold start — full scan" >&2
    CHANGED_FILES=$(git diff --cached --name-only 2>/dev/null)
    SCAN_MODE="cold"
else
    CHANGED_FILES=$(git diff --name-only "${LAST_SHA}..HEAD" 2>/dev/null)
    STAGED_FILES=$(git diff --cached --name-only 2>/dev/null)
    # Union: changed since last pass + currently staged
    CHANGED_FILES=$(echo -e "${CHANGED_FILES}\n${STAGED_FILES}" | sort -u | grep -v '^$')
    SCAN_MODE="incremental"
fi

# Detect tiers from file paths
HAS_BACKEND=false; HAS_FRONTEND=false
while IFS= read -r f; do
    [[ "$f" == backend/* ]] || [[ "$f" == src/* ]] || [[ "$f" == app/* ]] || [[ "$f" == *.py ]] && HAS_BACKEND=true
    [[ "$f" == frontend/* ]] || [[ "$f" == *.tsx ]] || [[ "$f" == *.ts ]] || [[ "$f" == *.jsx ]] && HAS_FRONTEND=true
done <<< "$CHANGED_FILES"

echo "GATE: scope=${SCAN_MODE} | backend=${HAS_BACKEND} | frontend=${HAS_FRONTEND}" >&2

# ── STEP 5: SECRETS SCAN ─────────────────────────────────────────────────────
SECRETS_FOUND=0
if git diff --cached --diff-filter=ACMR -p 2>/dev/null | \
    grep -iE '(api[_-]?key|secret|password|token|private[_-]?key|aws_access|BEGIN (RSA|EC|OPENSSH|PGP))' 2>/dev/null | \
    grep -v '^---\|^+++\|^@@\|^#\|placeholder\|example\|REDACTED' 2>/dev/null | \
    grep -q .; then
    SECRETS_FOUND=1
fi
if [ "$SECRETS_FOUND" -eq 1 ]; then
    echo -e "${RED}GATE BLOCK: Potential secret detected in diff. Review staged changes.${RESET}" >&2
    OUTCOME="block:secrets"
    _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
    exit 1
fi

# ── STEP 6: BACKEND CHECKS ───────────────────────────────────────────────────
COVERAGE_THRESHOLD=$(_json_get "$GATE_STATE" "thresholds.coverage_pct")
COVERAGE_THRESHOLD="${COVERAGE_THRESHOLD:-80}"
COMPLEXITY_THRESHOLD=$(_json_get "$GATE_STATE" "thresholds.complexity_max")
COMPLEXITY_THRESHOLD="${COMPLEXITY_THRESHOLD:-10}"

if $HAS_BACKEND && [ -n "$LINT_CMD" ]; then
    echo "GATE: running lint..." >&2
    if ! _run_with_timeout "lint" bash -c "$LINT_CMD"; then
        echo -e "${RED}GATE BLOCK: lint failed.${RESET}" >&2
        OUTCOME="block:lint"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

if $HAS_BACKEND && [ -n "$TYPE_CMD" ]; then
    echo "GATE: running type check..." >&2
    if ! _run_with_timeout "type-check" bash -c "$TYPE_CMD"; then
        echo -e "${RED}GATE BLOCK: type check failed.${RESET}" >&2
        OUTCOME="block:type"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

if $HAS_BACKEND && [ -n "$TEST_CMD" ]; then
    echo "GATE: running tests + coverage (threshold: ${COVERAGE_THRESHOLD}%)..." >&2
    # Tests use hard timeout: a hung test suite is a blocking condition
    TIMEOUT_SEC=$(_json_get "$GATE_STATE" "thresholds.command_timeout_sec")
    TIMEOUT_SEC="${TIMEOUT_SEC:-30}"
    TEST_TIMEOUT=$(( TIMEOUT_SEC * 10 ))   # tests get 10x normal timeout
    if command -v timeout >/dev/null 2>&1; then
        if ! timeout "$TEST_TIMEOUT" bash -c "$TEST_CMD" 2>&1; then
            echo -e "${RED}GATE BLOCK: tests/coverage failed or timed out.${RESET}" >&2
            OUTCOME="block:tests"
            _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
            exit 1
        fi
    else
        if ! bash -c "$TEST_CMD"; then
            echo -e "${RED}GATE BLOCK: tests/coverage failed.${RESET}" >&2
            OUTCOME="block:tests"
            _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
            exit 1
        fi
    fi
fi

if $HAS_BACKEND && [ -n "$COMPLEXITY_CMD" ]; then
    echo "GATE: running complexity check (threshold: cc <= ${COMPLEXITY_THRESHOLD})..." >&2
    COMPLEXITY_OUTPUT=$(_run_with_timeout "complexity" bash -c "$COMPLEXITY_CMD" 2>&1 || true)
    if [ -n "$COMPLEXITY_OUTPUT" ]; then
        echo -e "${RED}GATE BLOCK: complexity exceeds threshold (cc > ${COMPLEXITY_THRESHOLD}):\n${COMPLEXITY_OUTPUT}${RESET}" >&2
        OUTCOME="block:complexity"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

# ── STEP 7: FRONTEND CHECKS ───────────────────────────────────────────────────
if $HAS_FRONTEND && [ -n "$FRONTEND_LINT_CMD" ]; then
    echo "GATE: running frontend lint..." >&2
    if ! _run_with_timeout "frontend-lint" bash -c "$FRONTEND_LINT_CMD"; then
        echo -e "${RED}GATE BLOCK: frontend lint failed.${RESET}" >&2
        OUTCOME="block:frontend-lint"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

if $HAS_FRONTEND && [ -n "$FRONTEND_TYPE_CMD" ]; then
    echo "GATE: running frontend type check..." >&2
    if ! _run_with_timeout "frontend-type" bash -c "$FRONTEND_TYPE_CMD"; then
        echo -e "${RED}GATE BLOCK: frontend type check failed.${RESET}" >&2
        OUTCOME="block:frontend-type"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

if $HAS_FRONTEND && [ -n "$FRONTEND_TEST_CMD" ]; then
    echo "GATE: running frontend tests..." >&2
    if ! _run_with_timeout "frontend-tests" bash -c "$FRONTEND_TEST_CMD"; then
        echo -e "${RED}GATE BLOCK: frontend tests failed.${RESET}" >&2
        OUTCOME="block:frontend-tests"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

# ── STEP 8: ALL CHECKS PASSED — advance ledger ────────────────────────────────
# CRITICAL: last_pass_sha is written ONLY here, after all checks exit 0.
# Never write it on entry or on cold-start — a mid-run block would poison the ledger.
if [ -f "$GATE_STATE" ]; then
    _json_set "$GATE_STATE" "last_pass_sha" "\"${HEAD_SHA}\""
    _json_set "$GATE_STATE" "last_pass_timestamp" "\"${NOW_ISO}\""
    _json_set "$GATE_STATE" "token.token_spent_today" "$TOTAL_SPENT"
    # Clear session spend tmp after accumulating
    rm -f "$SESSION_SPEND"
fi

_json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "pass"

echo -e "${GREEN}GATE PASS: all checks clean | branch=${CURRENT_BRANCH} | mode=${SCAN_MODE} | token=${TOTAL_SPENT}/${TOKEN_BUDGET}${RESET}" >&2
exit 0
