#!/usr/bin/env bash
# gate.sh — Claude Code enforcement gate (generated by install.sh, committed to .githooks/)
# Called by pre-commit and pre-push hooks. Never invoke directly in CI.
#
# STACK-SPECIFIC VARIABLES (filled by init — do not edit manually):
# CRITICAL: All commands must use CHANGED_FILES scoping on large repos (>100k LOC).
# Defaults below apply scoping via git diff. At 1M+ LOC, global scans exceed 30s timeout.
TEST_CMD="${TEST_CMD:-}"   # Set by init with scoped test selection
LINT_CMD="${LINT_CMD:-}"   # Set by init with scoped file paths
TYPE_CMD="${TYPE_CMD:-}"   # Set by init with scoped analysis
COVERAGE_CMD="${COVERAGE_CMD:-}"   # Set by init with affected coverage only
COMPLEXITY_CMD="${COMPLEXITY_CMD:-}"   # Set by init with affected functions only
FRONTEND_TEST_CMD="${FRONTEND_TEST_CMD:-}"   # empty = skip
FRONTEND_LINT_CMD="${FRONTEND_LINT_CMD:-}"   # empty = skip
FRONTEND_TYPE_CMD="${FRONTEND_TYPE_CMD:-}"   # empty = skip

# TEST EXECUTION FLAG: Set --run-tests=true to enable. Default = false (skip tests).
# Usage: --run-tests=true git commit -m "message"
# Or:    --run-tests=true git push
RUN_TESTS="${RUN_TESTS:-false}"
# Allow override via commit message: if message contains [run-tests] or [--run-tests=true], enable
if git log -1 --pretty=%B 2>/dev/null | grep -qiE '\[.*run-?tests.*\]|--run-?tests'; then
    RUN_TESTS="true"
fi

set -euo pipefail

# ── Constants ────────────────────────────────────────────────────────────────
GATE_STATE=".claude/gate_state.json"
SESSION_SPEND=".claude/session_spend.tmp"
GIT_CACHE=".claude/git_cache.json"
BASELINE=".claude/baseline.json"
ORG_POLICY="${HOME}/.claude/org_policy.json"

# Color codes ONLY when stderr is a real terminal. In a VS Code / IDE extension
# wrapper (non-TTY), raw ANSI escapes render as garbage and can freeze the editor
# output pane — so emit plain text there. Works seamlessly in CLI, desktop app,
# and IDE extensions alike.
if [ -t 2 ]; then
    RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; RESET='\033[0m'
else
    RED=''; YELLOW=''; GREEN=''; RESET=''
fi

# ── Helpers ───────────────────────────────────────────────────────────────────

_json_get() {
    # Usage: _json_get <file> <key>  — naive but dependency-free jq substitute
    python3 -c "
import json, sys
with open('$1') as f:
    d = json.load(f)
keys = '$2'.split('.')
v = d
for k in keys:
    if k == '': break
    v = v.get(k, '')
print(v if v is not None else '')
" 2>/dev/null || echo ""
}

_json_set() {
    # Usage: _json_set <file> <key> <value>
    python3 -c "
import json, sys
with open('$1') as f:
    d = json.load(f)
keys = '$2'.split('.')
obj = d
for k in keys[:-1]:
    obj = obj.setdefault(k, {})
val = '$3'
try:
    obj[keys[-1]] = json.loads(val)
except:
    obj[keys[-1]] = val
with open('$1', 'w') as f:
    json.dump(d, f, indent=2)
" 2>/dev/null
}

_json_append_audit() {
    # Append one entry to token.token_audit_log; prune entries older than 90 days
    python3 -c "
import json, sys
from datetime import datetime, timedelta
with open('$GATE_STATE') as f:
    d = json.load(f)
entry = {'timestamp': '$1', 'trigger': '$2', 'spend_at_run': $3, 'outcome': '$4'}
log = d.get('token', {}).get('token_audit_log', [])
log.append(entry)
cutoff = (datetime.utcnow() - timedelta(days=90)).isoformat()
log = [e for e in log if e.get('timestamp','') >= cutoff]
d.setdefault('token', {})['token_audit_log'] = log
with open('$GATE_STATE', 'w') as f:
    json.dump(d, f, indent=2)
" 2>/dev/null
}

# ── Fingerprint receipt helpers (spec §4.2 — two distinct forms) ──────────────
# COMMIT_TREE_FP keys receipts (pre-commit writes, pre-push verifies).
# Receipts are pruned to the most recent 50 to bound ledger growth.
_receipt_write() {
    # Usage: _receipt_write <tree_hash> <branch>
    [ -f "$GATE_STATE" ] || return 0
    [ -n "$1" ] || return 0
    python3 -c "
import json
from datetime import datetime, timezone
with open('$GATE_STATE') as f:
    d = json.load(f)
r = d.setdefault('receipts', {})
r['$1'] = {'timestamp': datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'), 'branch': '$2', 'outcome': 'pass'}
# Bound growth: keep the 50 most recent by timestamp
if len(r) > 50:
    keep = sorted(r.items(), key=lambda kv: kv[1].get('timestamp',''), reverse=True)[:50]
    d['receipts'] = dict(keep)
with open('$GATE_STATE', 'w') as f:
    json.dump(d, f, indent=2)
" 2>/dev/null
}

_receipt_has_pass() {
    # Usage: _receipt_has_pass <tree_hash> -> echoes "yes" or "no"
    if [ ! -f "$GATE_STATE" ] || [ -z "$1" ]; then echo "no"; return 0; fi
    python3 -c "
import json
try:
    with open('$GATE_STATE') as f:
        d = json.load(f)
    r = d.get('receipts', {}).get('$1', {})
    print('yes' if r.get('outcome') == 'pass' else 'no')
except Exception:
    print('no')
" 2>/dev/null || echo "no"
}

_run_with_timeout() {
    local timeout_sec cmd_label
    timeout_sec=$(_json_get "$GATE_STATE" "thresholds.command_timeout_sec")
    timeout_sec="${timeout_sec:-30}"
    cmd_label="$1"; shift
    # Use timeout(1) if available; fall back to plain execution
    if command -v timeout >/dev/null 2>&1; then
        if ! timeout "$timeout_sec" "$@" 2>&1; then
            local exit_code=$?
            if [ $exit_code -eq 124 ]; then
                echo -e "${YELLOW}⚠ TIMEOUT: '$cmd_label' exceeded ${timeout_sec}s — killed and logged${RESET}" >&2
                _json_append_audit "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "timeout" 0 "timeout:${cmd_label}"
                return 1
            fi
            return $exit_code
        fi
    else
        "$@"
    fi
}

# ── CRASH GUARD ───────────────────────────────────────────────────────────────
# Any unhandled non-zero exit from gate.sh is a BLOCK, never a silent pass.
# stderr is emitted verbatim so the engineer sees the root cause.
_crash_handler() {
    echo -e "${RED}GATE CRASH at line $1 — exit $2. Commit blocked. Fix gate.sh or contact platform team.${RESET}" >&2
    exit 1
}
trap '_crash_handler ${LINENO} $?' ERR

# ── GATE_STATE guard ──────────────────────────────────────────────────────────
if [ ! -f "$GATE_STATE" ]; then
    echo -e "${YELLOW}⚠ gate_state.json not found — running cold start (full scan)${RESET}" >&2
fi

# ── STEP 1: BRANCH VALIDATION ─────────────────────────────────────────────────
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [[ "$CURRENT_BRANCH" =~ ^(main|master|develop)$ ]]; then
    echo -e "${RED}BRANCH BLOCK: Direct commits to '$CURRENT_BRANCH' are forbidden.${RESET}" >&2
    echo "Create a feature/bugfix/hotfix/release branch." >&2
    exit 1
fi

BRANCH_PREFIX="${CURRENT_BRANCH%%/*}"
if [[ ! "$BRANCH_PREFIX" =~ ^(feature|bugfix|hotfix|release)$ ]] && [ -n "$CURRENT_BRANCH" ]; then
    echo -e "${YELLOW}⚠ Branch '$CURRENT_BRANCH' does not follow Gitflow naming.${RESET}" >&2
    # Warn only — do not block; human-facing warning is sufficient at gate level
fi

# ── STEP 2: TOKEN HARNESS ─────────────────────────────────────────────────────
TODAY=$(date +%Y-%m-%d)
GATE_TRIGGER="${GATE_TRIGGER:-pre-commit}"   # pre-commit or pre-push hook sets this
NOW_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Read org-level budget ceiling
ORG_BUDGET=""
if [ -f "$ORG_POLICY" ]; then
    ORG_BUDGET=$(python3 -c "import json; d=json.load(open('$ORG_POLICY')); print(d.get('TOKEN_BUDGET',''))" 2>/dev/null || echo "")
fi

TOKEN_BUDGET=""
if [ -f "$GATE_STATE" ]; then
    TOKEN_BUDGET=$(_json_get "$GATE_STATE" "token.token_budget")
fi
TOKEN_BUDGET="${TOKEN_BUDGET:-50000}"

# Org ceiling wins if set and lower than repo setting
if [ -n "$ORG_BUDGET" ] && [ "$ORG_BUDGET" -lt "$TOKEN_BUDGET" ] 2>/dev/null; then
    TOKEN_BUDGET="$ORG_BUDGET"
fi

# Date-roll reset
if [ -f "$GATE_STATE" ]; then
    LAST_RESET=$(_json_get "$GATE_STATE" "token.token_last_reset")
    if [ "$LAST_RESET" != "$TODAY" ]; then
        _json_set "$GATE_STATE" "token.token_spent_today" "0"
        _json_set "$GATE_STATE" "token.token_last_reset" "\"$TODAY\""
    fi
fi

# Accumulate session spend from tmp file
SESSION_SPEND_VAL=0
if [ -f "$SESSION_SPEND" ]; then
    SESSION_SPEND_VAL=$(cat "$SESSION_SPEND" 2>/dev/null | tr -cd '0-9' || echo "0")
    SESSION_SPEND_VAL="${SESSION_SPEND_VAL:-0}"
fi

SPENT_TODAY=0
if [ -f "$GATE_STATE" ]; then
    SPENT_TODAY=$(_json_get "$GATE_STATE" "token.token_spent_today")
    SPENT_TODAY="${SPENT_TODAY:-0}"
fi
TOTAL_SPENT=$(( SPENT_TODAY + SESSION_SPEND_VAL ))

# Threshold evaluation
OUTCOME="pass"
if [ "$TOKEN_BUDGET" -gt 0 ] 2>/dev/null; then
    PCT=$(( TOTAL_SPENT * 100 / TOKEN_BUDGET ))
    if [ "$PCT" -ge 100 ]; then
        echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2
        echo "TOKEN HARD BLOCK — Org-wide daily budget exhausted." >&2
        echo "Spent: ${TOTAL_SPENT} / Budget: ${TOKEN_BUDGET} tokens" >&2
        echo "Resets: tomorrow (${TODAY} 00:00 UTC)" >&2
        echo "To raise budget: update ~/.claude/org_policy.json TOKEN_BUDGET (requires human PR)." >&2
        echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}" >&2
        OUTCOME="hard_block"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "hard_block"
        [ -f "$GATE_STATE" ] && _json_set "$GATE_STATE" "token.token_spent_today" "$TOTAL_SPENT"
        exit 1
    elif [ "$PCT" -ge 80 ]; then
        echo -e "${YELLOW}⚠ TOKEN WARNING: ${PCT}% of daily budget used (${TOTAL_SPENT}/${TOKEN_BUDGET})${RESET}" >&2
        OUTCOME="warn"
    fi
fi

# ── STEP 3: GRAPH STALENESS CHECK ─────────────────────────────────────────────
if [ -f ".mcp.json" ] && [ -f "$GATE_STATE" ]; then
    LAST_BUILD=$(_json_get "$GATE_STATE" "mcp_graph.last_build_timestamp")
    if [ -n "$LAST_BUILD" ] && [ "$LAST_BUILD" != "null" ]; then
        # Check if last build > 7 days ago (portable: compare epoch seconds)
        LAST_BUILD_EPOCH=$(date -d "$LAST_BUILD" +%s 2>/dev/null || date -j -f "%Y-%m-%dT%H:%M:%SZ" "$LAST_BUILD" +%s 2>/dev/null || echo "0")
        NOW_EPOCH=$(date +%s)
        STALE_THRESHOLD=$(( 7 * 24 * 3600 ))
        if [ $(( NOW_EPOCH - LAST_BUILD_EPOCH )) -gt "$STALE_THRESHOLD" ]; then
            echo -e "${YELLOW}⚠ GRAPH STALE: last built >7 days ago. Run: code-review-graph build${RESET}" >&2
        fi
    fi
fi

# ── STEP 4: DETERMINE SCAN SCOPE ──────────────────────────────────────────────
# Incremental scan from last_pass_sha; cold start if null or missing
LAST_SHA=""
if [ -f "$GATE_STATE" ]; then
    LAST_SHA=$(_json_get "$GATE_STATE" "last_pass_sha")
fi

HEAD_SHA=$(git rev-parse HEAD 2>/dev/null || echo "INIT")

if [ -z "$LAST_SHA" ] || [ "$LAST_SHA" = "null" ] || [ "$LAST_SHA" = "" ]; then
    echo "GATE: cold start — full scan" >&2
    CHANGED_FILES=$(git diff --cached --name-only 2>/dev/null)
    SCAN_MODE="cold"
else
    CHANGED_FILES=$(git diff --name-only "${LAST_SHA}..HEAD" 2>/dev/null)
    STAGED_FILES=$(git diff --cached --name-only 2>/dev/null)
    # Union: changed since last pass + currently staged
    CHANGED_FILES=$(echo -e "${CHANGED_FILES}\n${STAGED_FILES}" | sort -u | grep -v '^$')
    SCAN_MODE="incremental"
fi

# Detect tiers from file paths
HAS_BACKEND=false; HAS_FRONTEND=false
while IFS= read -r f; do
    [[ "$f" == backend/* ]] || [[ "$f" == src/* ]] || [[ "$f" == app/* ]] || [[ "$f" == *.py ]] && HAS_BACKEND=true
    [[ "$f" == frontend/* ]] || [[ "$f" == *.tsx ]] || [[ "$f" == *.ts ]] || [[ "$f" == *.jsx ]] && HAS_FRONTEND=true
done <<< "$CHANGED_FILES"

echo "GATE: scope=${SCAN_MODE} | backend=${HAS_BACKEND} | frontend=${HAS_FRONTEND}" >&2

# ── STEP 4.3: CORE_FILES RATCHET → TIER-3 DETECTION ──────────────────────────
# If any changed file matches a CORE_FILES glob, escalate to TIER-3:
# full test suite (no changed-file scoping) + mandatory test run even at commit.
CORE_FILES_TOUCHED=false
if [ -f "$GATE_STATE" ]; then
    CORE_MATCH=$(python3 -c "
import json, fnmatch
try:
    with open('$GATE_STATE') as f:
        d = json.load(f)
    patterns = d.get('core_files', []) or []
    changed = '''$CHANGED_FILES'''.split('\n')
    hit = next((c for c in changed if c and any(fnmatch.fnmatch(c, p) for p in patterns)), '')
    print(hit)
except Exception:
    print('')
" 2>/dev/null || echo "")
    if [ -n "$CORE_MATCH" ]; then
        CORE_FILES_TOUCHED=true
        echo -e "${YELLOW}GATE: TIER-3 — CORE_FILES touched ('${CORE_MATCH}'). Full suite + mandatory tests.${RESET}" >&2
    fi
fi

# ── STEP 4.5: FINGERPRINT FORMS (spec §4.2 — never conflate) ─────────────────
# WORKING_TREE_FP: working-tree state, keys the in-session ledger skip ONLY.
# COMMIT_TREE_FP : the tree actually being committed/pushed, keys receipts.
WORKING_TREE_FP=""
COMMIT_TREE_FP=""
WORKING_TREE_FP=$( { git rev-parse 'HEAD^{tree}' 2>/dev/null; git diff -p 2>/dev/null; git diff --cached -p 2>/dev/null; } | shasum 2>/dev/null | awk '{print $1}' || echo "")

if [ "$GATE_TRIGGER" = "pre-push" ]; then
    COMMIT_TREE_FP=$(git rev-parse 'HEAD^{tree}' 2>/dev/null || echo "")
    # Receipt fast-path: a prior pre-commit run already verified this exact tree.
    if [ "$(_receipt_has_pass "$COMMIT_TREE_FP")" = "yes" ]; then
        echo -e "${GREEN}GATE: pre-push receipt verified for tree ${COMMIT_TREE_FP:0:12} — checks already passed at commit.${RESET}" >&2
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "pass:receipt"
        exit 0
    fi
    # No receipt → run full mechanical verification now (tests forced on).
    echo -e "${YELLOW}GATE: no pre-commit receipt for this tree — running full mechanical checks before push.${RESET}" >&2
    RUN_TESTS="true"
else
    COMMIT_TREE_FP=$(git write-tree 2>/dev/null || echo "")
fi

# Mechanical test enforcement: push and CI always run tests; CORE_FILES always run tests.
if [ "$GATE_TRIGGER" = "pre-push" ] || [ "$GATE_TRIGGER" = "ci" ] || [ "$CORE_FILES_TOUCHED" = true ]; then
    RUN_TESTS="true"
fi

# ── STEP 5: SECRETS SCAN ─────────────────────────────────────────────────────
SECRETS_FOUND=0
if git diff --cached --diff-filter=ACMR -p 2>/dev/null | \
    grep -iE '(api[_-]?key|secret|password|token|private[_-]?key|aws_access|BEGIN (RSA|EC|OPENSSH|PGP))' 2>/dev/null | \
    grep -v '^---\|^+++\|^@@\|^#\|placeholder\|example\|REDACTED' 2>/dev/null | \
    grep -q .; then
    SECRETS_FOUND=1
fi
if [ "$SECRETS_FOUND" -eq 1 ]; then
    echo -e "${RED}GATE BLOCK: Potential secret detected in diff. Review staged changes.${RESET}" >&2
    OUTCOME="block:secrets"
    _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
    exit 1
fi

# ── STEP 5.5: SCOPED COMMAND INJECTION ──────────────────────────────────────
# CRITICAL FOR 100k+ LOC: Scope all linters, type-checkers, and tests to changed
# files only. Global scans exceed 30s timeout on large repos. The init process
# fills these variables with stack-specific scoped commands using CHANGED_FILES.
# If init leaves them empty, gate.sh derives scoped versions automatically here.

# ── Dynamic Stack Inference (§6.0) ───────────────────────────────────────────
# Infer test runners from repo topology — never default to a static pytest command.

_has_playwright_config() {
    [ -f "playwright.config.ts" ] || [ -f "playwright.config.js" ] || \
    [ -f "playwright.config.mjs" ] || \
    { [ -f "package.json" ] && grep -q '@playwright/test' package.json 2>/dev/null; }
}

_infer_backend_test_cmd() {
    local changed="$1"
    local py_changed go_changed js_changed

    # Python: pytest via config manifests
    if [ -f "pytest.ini" ] || [ -f "conftest.py" ] || \
       { [ -f "pyproject.toml" ] && grep -q '\[tool\.pytest' pyproject.toml 2>/dev/null; } || \
       { [ -f "setup.cfg" ] && grep -q '\[tool:pytest\]' setup.cfg 2>/dev/null; } || \
       { ls requirements*.txt >/dev/null 2>&1 && grep -qE '^pytest' requirements*.txt 2>/dev/null; }; then
        py_changed=$(echo "$changed" | grep -E '\.py$' | tr '\n' ' ' || true)
        if [ -n "$py_changed" ]; then
            echo "pytest -x -q --tb=short ${py_changed} 2>&1 | head -100"
        else
            echo "pytest -x -q --tb=short 2>&1 | head -100"
        fi
        return 0
    fi

    # Node/JS: jest, vitest, or npm test script
    if [ -f "package.json" ]; then
        js_changed=$(echo "$changed" | grep -E '\.(ts|tsx|js|jsx)$' | tr '\n' ' ' || true)
        if grep -q '"jest"' package.json 2>/dev/null || \
           grep -qE '"test".*jest' package.json 2>/dev/null; then
            if [ -n "$js_changed" ]; then
                echo "npm test -- --passWithNoTests --findRelatedTests ${js_changed} 2>&1 | head -100"
            else
                echo "npm test -- --passWithNoTests 2>&1 | head -100"
            fi
            return 0
        elif grep -q 'vitest' package.json 2>/dev/null; then
            echo "npx vitest run --passWithNoTests 2>&1 | head -100"
            return 0
        elif grep -q '"test"' package.json 2>/dev/null; then
            echo "npm test 2>&1 | head -100"
            return 0
        fi
    fi

    # Go
    if [ -f "go.mod" ]; then
        go_changed=$(echo "$changed" | grep -E '\.go$' | while read -r f; do dirname "$f"; done 2>/dev/null | sort -u | sed 's|^|./|' | tr '\n' ' ' || true)
        if [ -n "$go_changed" ]; then
            echo "go test ${go_changed} -count=1 2>&1 | head -100"
        else
            echo "go test ./... -count=1 2>&1 | head -100"
        fi
        return 0
    fi

    # Rust
    if [ -f "Cargo.toml" ]; then
        echo "cargo test --quiet 2>&1 | head -100"
        return 0
    fi

    # Java/Kotlin — Maven or Gradle
    if [ -f "pom.xml" ]; then
        echo "mvn -q test 2>&1 | head -100"
        return 0
    fi
    if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
        echo "./gradlew test --quiet 2>&1 | head -100"
        return 0
    fi

    echo ""
}

_infer_playwright_cmd() {
    local changed="$1"
    if ! _has_playwright_config; then
        echo ""
        return 0
    fi
    local pw_specs ui_touched
    pw_specs=$(echo "$changed" | grep -E '\.(spec|e2e)\.(ts|js|mjs)$|/e2e/' | tr '\n' ' ' || true)
    if [ -n "$pw_specs" ]; then
        echo "npx playwright test ${pw_specs} 2>&1 | head -100"
    else
        ui_touched=$(echo "$changed" | grep -E '(routes/|pages/|components/|frontend/|presentation/|\.tsx$|\.jsx$|nginx\.conf|proxy)' || true)
        if [ -n "$ui_touched" ] || [ -n "$changed" ]; then
            echo "npx playwright test 2>&1 | head -100"
        fi
    fi
}

# Build execution queue: init overrides first, then inferred runners.
# TIER-3 (CORE_FILES touched) runs the FULL suite — pass empty scope so inference
# does not narrow to changed files.
if [ "$CORE_FILES_TOUCHED" = true ]; then
    TEST_SCOPE_FILES=""
else
    TEST_SCOPE_FILES="$CHANGED_FILES"
fi

TEST_RUNNERS=()
if [ -n "$TEST_CMD" ]; then
    TEST_RUNNERS+=("$TEST_CMD")
else
    _INFERRED_BACKEND=$(_infer_backend_test_cmd "$TEST_SCOPE_FILES")
    [ -n "$_INFERRED_BACKEND" ] && TEST_RUNNERS+=("$_INFERRED_BACKEND")
fi

if [ -n "$FRONTEND_TEST_CMD" ]; then
    TEST_RUNNERS+=("$FRONTEND_TEST_CMD")
else
    _INFERRED_PW=$(_infer_playwright_cmd "$TEST_SCOPE_FILES")
    [ -n "$_INFERRED_PW" ] && TEST_RUNNERS+=("$_INFERRED_PW")
fi

if [ ${#TEST_RUNNERS[@]} -gt 0 ]; then
    echo "GATE: inferred test runners (${#TEST_RUNNERS[@]}): ${TEST_RUNNERS[*]}" >&2
fi

if [ -z "$LINT_CMD" ]; then
    # Scope linting to changed files
    LINT_CHANGED=$(echo "$CHANGED_FILES" | grep -E '\.(py)$' | tr '\n' ' ' || true)
    if [ -n "$LINT_CHANGED" ]; then
        LINT_CMD="ruff check $LINT_CHANGED"
    fi
fi

if [ -z "$TYPE_CMD" ]; then
    # Scope type-checking to changed files
    TYPE_CHANGED=$(echo "$CHANGED_FILES" | grep -E '\.(py)$' | tr '\n' ' ' || true)
    if [ -n "$TYPE_CHANGED" ]; then
        TYPE_CMD="mypy $TYPE_CHANGED --no-error-summary 2>&1 | head -50"
    fi
fi

if [ -z "$COMPLEXITY_CMD" ]; then
    # Scope complexity analysis to changed files only
    COMPLEXITY_CHANGED=$(echo "$CHANGED_FILES" | grep -E '\.(py)$' | tr '\n' ' ' || true)
    if [ -n "$COMPLEXITY_CHANGED" ]; then
        COMPLEXITY_CMD="radon cc -n C $COMPLEXITY_CHANGED"
    fi
fi

# ── STEP 6: BACKEND CHECKS ───────────────────────────────────────────────────
COVERAGE_THRESHOLD=$(_json_get "$GATE_STATE" "thresholds.coverage_pct")
COVERAGE_THRESHOLD="${COVERAGE_THRESHOLD:-80}"
COMPLEXITY_THRESHOLD=$(_json_get "$GATE_STATE" "thresholds.complexity_max")
COMPLEXITY_THRESHOLD="${COMPLEXITY_THRESHOLD:-10}"

if $HAS_BACKEND && [ -n "$LINT_CMD" ]; then
    echo "GATE: running lint..." >&2
    LINT_RC=0
    LINT_OUTPUT=$(bash -c "$LINT_CMD" 2>&1) || LINT_RC=$?

    # Identity-based debt ratchet (brownfield): when a populated baseline.json
    # exists, grandfather pre-existing findings and block only NEW identities.
    # Identity = "<normalized_path>|<rule_code>" (line excluded → format-insensitive).
    # Greenfield (no baseline) keeps zero-tolerance: any lint failure blocks.
    RATCHET_ACTIVE=false
    if [ -f "$BASELINE" ]; then
        RATCHET_ACTIVE=$(python3 -c "
import json
try:
    with open('$BASELINE') as f: b = json.load(f)
    print('true' if b.get('populated') and isinstance(b.get('lint_findings'), list) else 'false')
except Exception:
    print('false')
" 2>/dev/null || echo "false")
    fi

    if [ "$RATCHET_ACTIVE" = "true" ]; then
        NEW_FINDINGS=$(python3 -c "
import json, re, sys
with open('$BASELINE') as f: b = json.load(f)
baseline = set(b.get('lint_findings', []))
new = []
for line in '''$LINT_OUTPUT'''.splitlines():
    m = re.match(r'^([^:]+):\d+:\d+:\s+([A-Z]+[0-9]+)', line.strip())
    if not m:
        continue
    ident = m.group(1) + '|' + m.group(2)
    if ident not in baseline:
        new.append(ident)
for n in sorted(set(new)):
    print(n)
" 2>/dev/null || echo "__PARSE_FAIL__")
        if [ "$NEW_FINDINGS" = "__PARSE_FAIL__" ]; then
            # Unparseable linter format → fall back to exit-code enforcement.
            if [ "$LINT_RC" -ne 0 ]; then
                echo -e "${RED}GATE BLOCK: lint failed (ratchet unavailable for this linter format).${RESET}" >&2
                echo "$LINT_OUTPUT" | head -50 >&2
                OUTCOME="block:lint"; _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"; exit 1
            fi
        elif [ -n "$NEW_FINDINGS" ]; then
            echo -e "${RED}GATE BLOCK: new lint findings not in baseline (debt ratchet):${RESET}" >&2
            echo "$NEW_FINDINGS" | head -50 >&2
            OUTCOME="block:lint-ratchet"; _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"; exit 1
        else
            echo "GATE: lint clean against baseline (pre-existing debt grandfathered)." >&2
        fi
    else
        # No baseline → zero tolerance.
        if [ "$LINT_RC" -ne 0 ]; then
            echo -e "${RED}GATE BLOCK: lint failed.${RESET}" >&2
            echo "$LINT_OUTPUT" | head -50 >&2
            OUTCOME="block:lint"; _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"; exit 1
        fi
    fi
fi

if $HAS_BACKEND && [ -n "$TYPE_CMD" ]; then
    echo "GATE: running type check..." >&2
    if ! _run_with_timeout "type-check" bash -c "$TYPE_CMD"; then
        echo -e "${RED}GATE BLOCK: type check failed.${RESET}" >&2
        OUTCOME="block:type"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

# ── STEP 6.5: LAYER BOUNDARY SCAN ────────────────────────────────────────────
# Heuristic grep scan scoped to CHANGED_FILES only (never full-repo).
# Catches the two most common AI-generated layer violations:
#   1. SQL in presentation/routes layer (belongs only in repositories/)
#   2. HTTP framework imports in application/services layer (belongs only in routes/)
# Fires only if changed files land in known layer directories — stack-agnostic.
if $HAS_BACKEND && [ -n "$CHANGED_FILES" ]; then
    LAYER_VIOLATIONS=""
    while IFS= read -r _lf; do
        [ -z "$_lf" ] || [ ! -f "$_lf" ] && continue

        # Routes / controllers / presentation layer: must contain NO raw SQL
        if echo "$_lf" | grep -qiE '/(routes?|controllers?|presentation|views?|handlers?)/'; then
            _SQL=$(grep -nE '(SELECT|INSERT|UPDATE|DELETE|cursor\.execute|executemany|psycopg2\.connect)' "$_lf" 2>/dev/null | grep -v '^\s*#\|placeholder\|example' | head -3 || true)
            if [ -n "$_SQL" ]; then
                LAYER_VIOLATIONS="${LAYER_VIOLATIONS}ROUTES_HAS_SQL ${_lf}:\n${_SQL}\n"
            fi
        fi

        # Services / application layer: must contain NO raw SQL
        if echo "$_lf" | grep -qiE '/(services?|application|use.?cases?)/'; then
            _SQL=$(grep -nE '(SELECT|INSERT|UPDATE|DELETE|cursor\.execute|executemany|psycopg2\.connect)' "$_lf" 2>/dev/null | grep -v '^\s*#\|placeholder\|example' | head -3 || true)
            if [ -n "$_SQL" ]; then
                LAYER_VIOLATIONS="${LAYER_VIOLATIONS}SERVICE_HAS_SQL ${_lf}:\n${_SQL}\n"
            fi
        fi

        # Services / application layer: must NOT import HTTP framework directly
        if echo "$_lf" | grep -qiE '/(services?|application|use.?cases?)/'; then
            _HTTP=$(grep -nE '^(from fastapi|import fastapi|from flask|import flask|from django\.http|APIRouter|@app\.(get|post|put|delete|patch)\()' "$_lf" 2>/dev/null | head -3 || true)
            if [ -n "$_HTTP" ]; then
                LAYER_VIOLATIONS="${LAYER_VIOLATIONS}SERVICE_HAS_HTTP ${_lf}:\n${_HTTP}\n"
            fi
        fi
    done <<< "$CHANGED_FILES"

    if [ -n "$LAYER_VIOLATIONS" ]; then
        echo -e "${RED}GATE BLOCK: Layer boundary violation(s) detected in changed files:${RESET}" >&2
        echo -e "$LAYER_VIOLATIONS" | head -40 >&2
        echo "SQL belongs in repositories/ only. HTTP framework imports belong in routes/ only." >&2
        echo "Move the violating code to the correct layer before committing." >&2
        OUTCOME="block:layer-boundary"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
    echo "GATE: layer boundary scan clean." >&2
fi

_run_test_queue() {
    local runner_idx=0 total=${#TEST_RUNNERS[@]}
    local TIMEOUT_SEC TEST_TIMEOUT
    TIMEOUT_SEC=$(_json_get "$GATE_STATE" "thresholds.command_timeout_sec")
    TIMEOUT_SEC="${TIMEOUT_SEC:-30}"
    TEST_TIMEOUT=$(( TIMEOUT_SEC * 10 ))

    for runner in "${TEST_RUNNERS[@]}"; do
        runner_idx=$(( runner_idx + 1 ))
        echo "GATE: running test suite ${runner_idx}/${total}..." >&2
        if command -v timeout >/dev/null 2>&1; then
            if ! timeout "$TEST_TIMEOUT" bash -c "$runner" 2>&1; then
                echo -e "${RED}GATE BLOCK: test suite ${runner_idx}/${total} failed or timed out.${RESET}" >&2
                echo "  Command: ${runner}" >&2
                return 1
            fi
        else
            if ! bash -c "$runner"; then
                echo -e "${RED}GATE BLOCK: test suite ${runner_idx}/${total} failed.${RESET}" >&2
                echo "  Command: ${runner}" >&2
                return 1
            fi
        fi
    done
    return 0
}

if [ "$RUN_TESTS" = "true" ] && [ ${#TEST_RUNNERS[@]} -gt 0 ]; then
    echo "GATE: running ${#TEST_RUNNERS[@]} test suite(s) (coverage threshold: ${COVERAGE_THRESHOLD}%)..." >&2
    if ! _run_test_queue; then
        OUTCOME="block:tests"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi

    # ── COVERAGE GATE ─────────────────────────────────────────────────────────
    # Executes COVERAGE_CMD (set by init), parses the trailing percentage, and
    # blocks when line coverage drops below COVERAGE_THRESHOLD. Lowering the
    # threshold requires a human PR (gate_state.json is agent-immutable).
    if [ -n "$COVERAGE_CMD" ]; then
        echo "GATE: measuring coverage (min ${COVERAGE_THRESHOLD}%)..." >&2
        COV_OUTPUT=$(_run_with_timeout "coverage" bash -c "$COVERAGE_CMD" 2>&1 || true)
        COV_PCT=$(echo "$COV_OUTPUT" | grep -oE '[0-9]+(\.[0-9]+)?%' | tail -1 | tr -d '%')
        if [ -z "$COV_PCT" ]; then
            echo -e "${YELLOW}⚠ COVERAGE: could not parse a percentage from COVERAGE_CMD output. Recording NO_COVERAGE.${RESET}" >&2
            _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "warn:no_coverage_parse"
        else
            # Integer-truncate for a dependency-free comparison (e.g. 79.9 -> 79).
            COV_INT=${COV_PCT%.*}
            if [ "${COV_INT:-0}" -lt "$COVERAGE_THRESHOLD" ] 2>/dev/null; then
                echo -e "${RED}GATE BLOCK: coverage ${COV_PCT}% < ${COVERAGE_THRESHOLD}% threshold.${RESET}" >&2
                OUTCOME="block:coverage"
                _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
                exit 1
            fi
            echo -e "${GREEN}GATE: coverage ${COV_PCT}% ≥ ${COVERAGE_THRESHOLD}%.${RESET}" >&2
        fi
    else
        echo "GATE: no COVERAGE_CMD configured — recording NO_COVERAGE (set it at init to enforce the coverage gate)." >&2
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "warn:no_coverage_cmd"
    fi
elif [ "$RUN_TESTS" != "true" ] && [ ${#TEST_RUNNERS[@]} -gt 0 ]; then
    echo "GATE: tests opt-in at pre-commit (--run-tests=false). Mandatory at pre-push and on CORE_FILES changes." >&2
    echo "GATE: queued runners (not executed): ${TEST_RUNNERS[*]}" >&2
fi

if $HAS_BACKEND && [ -n "$COMPLEXITY_CMD" ]; then
    echo "GATE: running complexity check (threshold: cc <= ${COMPLEXITY_THRESHOLD})..." >&2
    COMPLEXITY_OUTPUT=$(_run_with_timeout "complexity" bash -c "$COMPLEXITY_CMD" 2>&1 || true)
    if [ -n "$COMPLEXITY_OUTPUT" ]; then
        echo -e "${RED}GATE BLOCK: complexity exceeds threshold (cc > ${COMPLEXITY_THRESHOLD}):\n${COMPLEXITY_OUTPUT}${RESET}" >&2
        OUTCOME="block:complexity"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

# ── STEP 7: FRONTEND CHECKS (lint/type only — tests run via TEST_RUNNERS queue) ─
if $HAS_FRONTEND && [ -n "$FRONTEND_LINT_CMD" ]; then
    echo "GATE: running frontend lint..." >&2
    if ! _run_with_timeout "frontend-lint" bash -c "$FRONTEND_LINT_CMD"; then
        echo -e "${RED}GATE BLOCK: frontend lint failed.${RESET}" >&2
        OUTCOME="block:frontend-lint"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

if $HAS_FRONTEND && [ -n "$FRONTEND_TYPE_CMD" ]; then
    echo "GATE: running frontend type check..." >&2
    if ! _run_with_timeout "frontend-type" bash -c "$FRONTEND_TYPE_CMD"; then
        echo -e "${RED}GATE BLOCK: frontend type check failed.${RESET}" >&2
        OUTCOME="block:frontend-type"
        _json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "$OUTCOME"
        exit 1
    fi
fi

# ── STEP 8: ALL CHECKS PASSED — write receipt + advance ledger ────────────────
# CRITICAL: last_pass_sha is written ONLY here, after all checks exit 0.
# Never write it on entry or on cold-start — a mid-run block would poison the ledger.
if [ -f "$GATE_STATE" ]; then
    _json_set "$GATE_STATE" "last_pass_sha" "\"${HEAD_SHA}\""
    _json_set "$GATE_STATE" "last_pass_timestamp" "\"${NOW_ISO}\""
    _json_set "$GATE_STATE" "token.token_spent_today" "$TOTAL_SPENT"
    # Clear session spend tmp after accumulating
    rm -f "$SESSION_SPEND"
fi

# Write the fingerprint receipt keyed by COMMIT_TREE_FP so pre-push can verify
# this exact tree was gated. Pre-commit writes the index tree; a no-receipt
# pre-push that reaches here writes its own (HEAD tree) receipt.
if [ -n "$COMMIT_TREE_FP" ]; then
    _receipt_write "$COMMIT_TREE_FP" "$CURRENT_BRANCH"
    echo -e "${GREEN}GATE: receipt written for tree ${COMMIT_TREE_FP:0:12}.${RESET}" >&2
fi

_json_append_audit "$NOW_ISO" "$GATE_TRIGGER" "$TOTAL_SPENT" "pass"

echo -e "${GREEN}GATE PASS: all checks clean | branch=${CURRENT_BRANCH} | mode=${SCAN_MODE} | tier3=${CORE_FILES_TOUCHED} | token=${TOTAL_SPENT}/${TOKEN_BUDGET}${RESET}" >&2
exit 0
