#!/usr/bin/env bash
# verify_governance_integrity.sh — deployed by install.sh to
# .githooks/verify_governance_integrity.sh, invoked by both CI
# (.github/workflows/gate.yml) and the bats test suite (test_helper.bash's
# run_ci_integrity_check). Single source of truth for the governance-file
# presence + content-hash check — extracted out of ci-gate.yml specifically
# so CI and the test suite can never drift out of sync with each other again
# (a prior audit found the hand-duplicated copy had silently gone stale).
set -euo pipefail

test -f .claude/gate_state.json || { echo "::error::.claude/gate_state.json missing"; exit 1; }
test -f .claude/gate_integrity.sha256 || { echo "::error::.claude/gate_integrity.sha256 missing — integrity pin stripped"; exit 1; }

# Every file listed inside .claude/gate_integrity.sha256 is checked for both
# presence and content in one shot. The manifest is generated by install.sh's
# _write_trust_root_settings via `sha256sum ... > .claude/gate_integrity.sha256`
# and covers every static, install.sh-owned governance script — not just
# gate.sh — so a PR that weakens the CI checker itself, the pre-commit/
# pre-push hooks, or the Bash-guard hook is caught the same way a weakened
# gate.sh is. This is the actual security boundary: .claude/gate_integrity.sha256
# and every file it lists must stay blocked from casual agent edits (see the
# trust-root deny-list in .claude/settings.json) and ideally be covered by
# CODEOWNERS + branch protection so only a human-reviewed PR can move the pin.
if command -v sha256sum >/dev/null 2>&1; then
    CHECK_CMD=(sha256sum -c .claude/gate_integrity.sha256)
elif command -v shasum >/dev/null 2>&1; then
    CHECK_CMD=(shasum -a 256 -c .claude/gate_integrity.sha256)
else
    echo "::error::Neither sha256sum nor shasum is available to verify the integrity manifest." >&2
    exit 1
fi

if ! "${CHECK_CMD[@]}"; then
    echo "::error::One or more governance files do not match the pinned integrity manifest (.claude/gate_integrity.sha256)." >&2
    echo "::error::If this change is legitimate, re-run install.sh --upgrade to regenerate the manifest, then commit it together with the changed file(s) under human review." >&2
    exit 1
fi
echo "Governance files present and integrity-verified."
